global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 15s
  group_interval: 30s
  repeat_interval: 3m
  receiver: 'dingding'
receivers:
- name: 'dingding'
  webhook_configs:
  - url: 'http://192.168.33.200:10080/alert?token=Bwbpyd39jXHm5DCXun4Z'
